### ISSUE TITLE
Aidl not found, please install

### ISSUE THREAD

**Issue by esaumukhwana** [esaumukhwana/energy#1]
While using the github action, I get the error , AIDL not found, is something wrong with my code? or the problem is with buildozer

**Comment by esaumukhwana** [comment]
arch for Aidl
# Aidl not found, please install it.
Traceback (most recent call last):
  File "/action/entrypoint.py", line 159, in <module>
    main()
  File "/action/entrypoint.py", line 27, in main
    run_command(env["INPUT_COMMAND"])
  File "/action/entrypoint.py", line 135, in run_command
    retcode = subprocess.check_call(command, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'buildozer android debug' returned non-zero exit status 1.
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Build with Buildozer



This is the error am getting
